### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by z3ntu** [raphinesse/angular-crumble#3]
Hello,
I can't seem to get crumble to work for my project. When I call `crumble.update({title: "sometitle"});`, I get the stacktrace 

> angular.js:13424 TypeError: Cannot read property 'length' of undefined
>     at k (http://localhost:5000/bower_components/angular/angular.min.js:102:437)
>     at Object.crumble.getCrumb (http://localhost:5000/bower_components/angular-crumble/crumble.js:28:16)
>     at build (http://localhost:5000/bower_components/angular-crumble/crumble.js:43:57)
>     at Object.crumble.update (http://localhost:5000/bower_components/angular-crumble/crumble.js:12:23)
>     at new <anonymous> (http://localhost:5000/js/honeypot.js:177:13)
>     at Object.instantiate (http://localhost:5000/bower_components/angular/angular.min.js:41:396)
>     at http://localhost:5000/bower_components/angular/angular.min.js:88:341
>     at link (http://localhost:5000/bower_components/angular-route/angular-route.min.js:7:274)
>     at ja (http://localhost:5000/bower_components/angular/angular.min.js:80:35)
>     at n (http://localhost:5000/bower_components/angular/angular.min.js:65:220) <div ng-view="" class="main-insert-view ng-scope">

. although the same code works fine in another line.
Source code for the whole project (specifically the JS & HTML code) is here: [link](https://github.com/MadeInSpengergasse/Honeypot/tree/crumble/static).
Javascript file is in the `js` folder, main page is the `index.html` file.
Do you know, what I did wrong? Thanks!

**Comment by raphinesse** [comment]
After taking a brief look at your code, it seems that you didn't define a `label` property for all routes that you use crumble on. What you pass to `crumble.update` is only an interpolation context for your label (so you can have dynamic labels).

Please double check the documentation on how to set the breadcrumb labels. Please do report if this resolved your issue or if the problem remains.

**Comment by z3ntu** [comment]
Wow, that fixed it, thanks... 
And do you mean with

> attach crumble to your main controller's scope 

something like [that](https://github.com/MadeInSpengergasse/Honeypot/blob/crumble/static/js/honeypot.js#L36)? 
btw that's an awesome angular extension!

**Comment by raphinesse** [comment]
Yes that looks good to me. I was just trying to say that you have to have access to the `crumble` object to render the breadcrumbs. How you do that exactly is entirely up to you. There's no magic involved whatsoever.

I am glad I could help you and that you enjoy using crumble :blush:

**Comment by z3ntu** [comment]
And is there a way to set a _dynamic_ parent (parent codesample from [the readme](https://github.com/raphinesse/angular-crumble#customizing-the-parent-relationship) works fine for static parents)? I don't have more experience with angular than what I used for this project (and I have close to zero knowledge about services, factories, etc).

**Comment by raphinesse** [comment]
From the readme:

> The parent of a node with path `path` is defined by the result of a call to `crumble.getParent(path)`. If the return value is falsy, the node is considered as the root.

So just redefine `crumble.getParent` the way you want it to behave. The example from the readme is just that: An example. Another one would be:

```
crumble.getParent = function (path) {
  return yourSuperDynamicParentFinderStrategy(path);
};
```

You can take a look at the [default implementation](https://github.com/raphinesse/angular-crumble/blob/v0.2.1/crumble.js#L15) too, if you want.

**Comment by z3ntu** [comment]
And that I understand this line correctly

```
return route && angular.isDefined(route.parent) ? route.parent : getParent(path);
```

So it returns `route` if it is not null, if it is, it looks if `route.parent` is defined, if yes return `route.parent` and otherwise call the default implementation with the path.
Is this correct (especially as I know the ternary operator)?

**Comment by raphinesse** [comment]
Parentheses added for clarity:

``` js
return (route && angular.isDefined(route.parent)) ? route.parent : getParent(path);
```

Read as "If we found a route definition for `path` and it has a `parent` property, then return the value of that property, else call the default implementation."

**Comment by z3ntu** [comment]
I got something that works for now: [my superDynamicParentFinderStrategyMethod](https://github.com/MadeInSpengergasse/Honeypot/blob/439804f4c9aa0ec0439ebc693e7db6449a096ad5/static/js/honeypot.js#L54) :D Thanks!!

**Comment by raphinesse** [comment]
You're welcome. I'm glad to see that you could make it work for your application's needs.
