### ISSUE TITLE
Could not find matching route definition for path /product/

### ISSUE THREAD

**Issue by AqquaBug** [raphinesse/angular-crumble#4]
I keep getting this error : Could not find matching route definition for path /product/.

My routeProvider setup is as follows 👍 

`zirveApp.config(['$routeProvider', function( $routeProvider){

$routeProvider.
when('/', {
    templateUrl : 'partials/home.html',
    controller : 'DefaultPageController',
    label: 'Home',

}).
when('/list', {
    templateUrl : 'views/list.html',
    controller : 'ListController',
    label: 'list',
}).
when('/contact',{
    templateUrl : 'views/contact.html',
    controller : 'ContactController',
    label: 'contact',
}).
when('/product/:productId',{
    templateUrl : 'partials/product.html',
    controller : 'ProductController',
    label : 'Product {{ name }}'

}).
otherwise({redirectTo: '/'});

}]);`

And my productController is : 

`.controller("ProductController", function($q, $scope, productService, $routeParams, $timeout, crumble)
{

  var thing = $routeParams.productId;

  // Updates the breadcrumb trail with the given context
 // crumble.update({name: 'orcun'});

   crumble.context = {name: thing};
    crumble.update();
...

});
`

Do you know why i keep getting this error ?

Thank you

**Comment by raphinesse** [comment]
I guess the error occurs because you use the default `get Parent` implementation. That means that `/product/` is the parent of `/product/:productId` and thus crumble will try to create an entry for `/product/` in the breadcrumbs of `/product/:productId`.

Either define a matching route or customize the parent relation to solve the issue. See the readme on how to achieve the latter.

**Comment by AqquaBug** [comment]
When i check the readme i see that implementation is this way : 

```
.when('/things/:thingId', {
        templateUrl: 'views/things/view.html',
        controller: 'ThingViewCtrl',
        // ...or markup as consumed by $interpolate
        label: '{{thing.title}}',
      })
```

and my implementation is same as : 

```
when('/product/:productId',{
templateUrl : 'partials/product.html',
controller : 'ProductController',
label : 'Product {{ name }}'
```

I am not sure what exactly you mean by 

> Either define a matching route

I read through the readme and i keep checking every step is same as your examples.

Do you have a working plunker example, or any full site example which is working, so i can exactly find out  where i am doing wrong.

Or simply : what should be my matching route ?
Thanks again for your prompt reply

**Comment by raphinesse** [comment]
But you don't have a route for just `/product`. Please read [the part of the readme on the parent relationship](https://github.com/raphinesse/angular-crumble/blob/master/README.md#customizing-the-parent-relationship) carefully.

I'm on my mobile, so I can't write a comprehensive example.

**Comment by AqquaBug** [comment]
Ok i finally just got angular-crumble working on a route for 

> /product

After reading the [parent relationship](https://github.com/raphinesse/angular-crumble/blob/master/README.md#customizing-the-parent-relationship) several times

I realise i have to put this in my run method and modify it according to my sites need ->

```
// Put this in your run method
var getParent = crumble.getParent;
crumble.getParent = function (path) {
  var route = crumble.getRoute(path);
  return route && angular.isDefined(route.parent) ? route.parent : getParent(path);
};
```

If we assume that my site is using the eact same structure as the USAGE example in the readme file which is this ->

```
      .when('/things/:thingId', {
        templateUrl: 'views/things/view.html',
        controller: 'ThingViewCtrl',
        // ...or markup as consumed by $interpolate
        label: '{{thing.title}}',
      })

```

How should i modify this ->

```
// Put this in your run method
var getParent = crumble.getParent;
crumble.getParent = function (path) {
  var route = crumble.getRoute(path);
  return // What the code needs to be for your USAGE path example to work here, which is : '/things/:thingId'
};
```

I am a newbie here so all your help is very appreciated, i believe many beginners might fall on this problem following readme instructions, how i should modify the code is not very clear to me

Thanks

**Comment by raphinesse** [comment]
That depends on what you expect to be displayed as the parent for `/things/:thingId`.

**Comment by raphinesse** [comment]
Here's a [project](https://gitlab.com/banana-code/participation-frontend/blob/master/app/scripts/app.js) where I used a custom parent relationship. Observe how the route definition of `/group/:groupId` has a parent property of `/groups`. Together with the code snippet from the readme that overrides the `getParent` method, this causes `/groups` to be the parent item instead of `/group`.

**Comment by AqquaBug** [comment]
Great, thank you, after looking at your code, all i had to do was to add this ->

`parent: '/'`

to the route; and worked like a charm,

Thank you very much for your help

**Comment by raphinesse** [comment]
I'm glad to hear that it works out for you now. If you have any suggestions to improve the documentation on the topic, your feedback would be appreciated.

**Comment by AqquaBug** [comment]
Hi yes, actually i would like to make  a simple suggestion, for newbies like myself;

It was not very clear to me that i could have used i the routeProvider config 

`parent : '/categories'`

in relation to this piece of code ;

```
// Put this in your run method
var getParent = crumble.getParent;
crumble.getParent = function (path) {
  var route = crumble.getRoute(path);
  return route && angular.isDefined(route.parent) ? route.parent : getParent(path);
};
```

Now i see that `route.parent` is actually referring to that `parent : '/categories'`

So i think it would be nice if you could add that `parent : '/categories'` bit information into routeProvider config example you have  [here](https://github.com/raphinesse/angular-crumble#set-route-labels).

Also for clarification, it would be great to have a very simple working plunker version of your crumble service.

Thank you again
