### ISSUE TITLE
Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by kabincs** [raphinesse/angular-crumble#5]
I have added the dependency crumble both in module and controller  and added label Like this
app.config(['$routeProvider', function ($routeProvider) {
  $routeProvider.when('/azurpage', {
    templateUrl:'app/applicationinsight/azurDummyPage/azurDummypage.tpl.html',
    controller:'azurpageCtrl',
    label: 'Home'
     });
}]).controller('appInsightCtrl',['$scope','sharedService','crumble',function ($scope,sharedService,$window,crumble) {
console.log(crumble.update());
}

BUT I AM GETTING THE ABOVE ERROR CAN YOU PLEASE HELP TO FIX THIS....IF ANY SIMPLE SAMPLE CODE YOU HAVE MEANS , PLEASE SHARE.

**Comment by raphinesse** [comment]
The above code is not even _syntactically_ correct. Can you provide a complete, properly formatted example of what you are trying to do? Preferable on a site like [JS Bin](https://jsbin.com). Otherwise I cannot help you.

**Comment by kabincs** [comment]
I have created sample plunker, doing routing in that routing added lable properties as you said and index.html i have added the html what is given is the site but it is not working. since i am new to angularjs i can't able to understand wat is going pleas help me.

https://plnkr.co/edit/EhmbTgZ4i2EAa6YsMpey?p=preview

**Comment by raphinesse** [comment]
1. You included an _ancient_ version of AngularJS. I don't know if crumble would work with that.
2. You did not update crumble, nor did you make it available in your scope, so you couldn't access it.
3. I can't give any further angular/JS lessons.

For details on how I fixed your plunker, diff it with [mine](https://plnkr.co/edit/Ogoz48BflNOUOi2dW4tC).
