### ISSUE TITLE
How to set a new root

### ISSUE THREAD

**Issue by pavei** [raphinesse/angular-crumble#6]
I want to set my root to /tixs, but i did't understand  how to do this when overriding crumble.getParent method.

**Comment by raphinesse** [comment]
> The parent of a node with path `p` is defined by the result of a call to `crumble.getParent(p)`. If the return value is falsy, the node is considered as the root.

So you just have to assign a function to `crumble.getParent` that returns something falsy if you reached your root and calls the original function otherwise.

**Comment by pavei** [comment]
I'm doing this on run method. What do you mean with 'return value is falsy'? Is return false, like i did? 

```
    var getParent = crumble.getParent;
    crumble.getParent = function (path) {

        var route = crumble.getRoute(path);

        if (path == '/tixs'){
            return false;
        }

        return route && angular.isDefined(route.parent) ? route.parent : getParent(path);
    };
```

**Comment by raphinesse** [comment]
Yes, that looks good so far. Does it work as intended?

If it does not work, you might have a trailing slash in `path`. Then you could try the following as a workaround:

``` js
if (path.matches(/^\/tixs\/?$/)) {
  return false;
}
```

I can't test it myself right now.

**Comment by pavei** [comment]
No, i'm getting stacktrace console error "/" path not found

Em 28 de out de 2016 22:32, "Raphael von der Grün" notifications@github.com
escreveu:

**Comment by raphinesse** [comment]
It would be helpful to include any relevant information, e.g. aforementioned stack trace.

Furthermore, have you tried my solution that accounts for the possibility of trailing slashes? (see above)

**Comment by pavei** [comment]
Yes, now it works. Thanks a lot for help! 

``` javascript
 if (path.match(/^\/tixs\/?$/)) {
            return false;
 }
```
